name: alth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - nuitka
    - numpy
    - ordered-set
    - pillow
    - pyinstaller
    - pyside6
    - pytoshop
    - six
    - type_extensions
    - unitypy